# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SoC/SoC.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC || ORIG_REF_NAME==SoC} -quiet] -quiet

# IP: bd/SoC/ip/SoC_xdma_0_0/SoC_xdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_xdma_0_0 || ORIG_REF_NAME==SoC_xdma_0_0} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_2/xdma_v4_1_8_blk_mem_64_noreg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_8_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_8_blk_mem_64_noreg_be} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_1/xdma_v4_1_8_blk_mem_64_reg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_8_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_8_blk_mem_64_reg_be} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/SoC_xdma_0_0_pcie4c_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==SoC_xdma_0_0_pcie4c_ip} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/ip_0/SoC_xdma_0_0_pcie4c_ip_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_xdma_0_0_pcie4c_ip_gt || ORIG_REF_NAME==SoC_xdma_0_0_pcie4c_ip_gt} -quiet] -quiet

# IP: bd/SoC/ip/SoC_util_ds_buf_0/SoC_util_ds_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_util_ds_buf_0 || ORIG_REF_NAME==SoC_util_ds_buf_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_axi_smc_0/SoC_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_axi_smc_0 || ORIG_REF_NAME==SoC_axi_smc_0} -quiet] -quiet

# Block Designs: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/bd_d7be.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_0/bd_d7be_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_1/bd_d7be_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_2/bd_d7be_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_3/bd_d7be_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_4/bd_d7be_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_5/bd_d7be_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_6/bd_d7be_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_7/bd_d7be_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_8/bd_d7be_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_9/bd_d7be_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_10/bd_d7be_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_11/bd_d7be_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_12/bd_d7be_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/SoC/ip/SoC_QuantLaneNet_0_0/SoC_QuantLaneNet_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_QuantLaneNet_0_0 || ORIG_REF_NAME==SoC_QuantLaneNet_0_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_system_ila_0_0/SoC_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_system_ila_0_0 || ORIG_REF_NAME==SoC_system_ila_0_0} -quiet] -quiet

# Block Designs: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/bd_5c78.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78 || ORIG_REF_NAME==bd_5c78} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_0/bd_5c78_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_ila_lib_0 || ORIG_REF_NAME==bd_5c78_ila_lib_0} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_1/bd_5c78_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_g_inst_0 || ORIG_REF_NAME==bd_5c78_g_inst_0} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_2/bd_5c78_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_0_aw_0 || ORIG_REF_NAME==bd_5c78_slot_0_aw_0} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_3/bd_5c78_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_0_w_0 || ORIG_REF_NAME==bd_5c78_slot_0_w_0} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_4/bd_5c78_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_0_b_0 || ORIG_REF_NAME==bd_5c78_slot_0_b_0} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_5/bd_5c78_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_0_ar_0 || ORIG_REF_NAME==bd_5c78_slot_0_ar_0} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_6/bd_5c78_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_0_r_0 || ORIG_REF_NAME==bd_5c78_slot_0_r_0} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_7/bd_5c78_slot_1_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_1_aw_0 || ORIG_REF_NAME==bd_5c78_slot_1_aw_0} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_8/bd_5c78_slot_1_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_1_w_0 || ORIG_REF_NAME==bd_5c78_slot_1_w_0} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_9/bd_5c78_slot_1_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_1_b_0 || ORIG_REF_NAME==bd_5c78_slot_1_b_0} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_10/bd_5c78_slot_1_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_1_ar_0 || ORIG_REF_NAME==bd_5c78_slot_1_ar_0} -quiet] -quiet

# IP: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_11/bd_5c78_slot_1_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_1_r_0 || ORIG_REF_NAME==bd_5c78_slot_1_r_0} -quiet] -quiet

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_2/xdma_v4_1_8_blk_mem_64_noreg_be_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_1/xdma_v4_1_8_blk_mem_64_reg_be_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/ip_0/synth/SoC_xdma_0_0_pcie4c_ip_gt_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/ip_0/synth/SoC_xdma_0_0_pcie4c_ip_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_xdma_0_0_pcie4c_ip_gt || ORIG_REF_NAME==SoC_xdma_0_0_pcie4c_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/SoC_xdma_0_0_pcie4c_ip_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==SoC_xdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/synth/SoC_xdma_0_0_pcie4c_ip_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/synth/SoC_xdma_0_0_pcie4c_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==SoC_xdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source/ip_pcie4_uscale_plus_x1y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_xdma_0_0_pcie4c_ip || ORIG_REF_NAME==SoC_xdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/SoC_xdma_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_xdma_0_0 || ORIG_REF_NAME==SoC_xdma_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/source/SoC_xdma_0_0_pcie4_uscaleplus_ip.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_xdma_0_0 || ORIG_REF_NAME==SoC_xdma_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/synth/SoC_xdma_0_0_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_util_ds_buf_0/SoC_util_ds_buf_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_util_ds_buf_0 || ORIG_REF_NAME==SoC_util_ds_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_util_ds_buf_0/SoC_util_ds_buf_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_util_ds_buf_0 || ORIG_REF_NAME==SoC_util_ds_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_util_ds_buf_0/SoC_util_ds_buf_0_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_1/bd_d7be_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_1/bd_d7be_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_5/bd_d7be_s00a2s_0_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_6/bd_d7be_sarn_0_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_7/bd_d7be_srn_0_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_8/bd_d7be_sawn_0_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_9/bd_d7be_swn_0_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_10/bd_d7be_sbn_0_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_11/bd_d7be_m00s2a_0_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5c78_ila_lib_0 || ORIG_REF_NAME==bd_5c78_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5c78_ila_lib_0 || ORIG_REF_NAME==bd_5c78_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_0/bd_5c78_ila_lib_0_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/bd_5c78_ooc.xdc

# XDC: /home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.gen/sources_1/bd/SoC/SoC_ooc.xdc
