#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : SoC.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Nov 09 17:34:18 JST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: SoC.sh [-help]
# usage: SoC.sh [-lib_map_path]
# usage: SoC.sh [-noclean_files]
# usage: SoC.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'SoC.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm gtwizard_ultrascale_v1_7_9 xil_defaultlib blk_mem_gen_v8_4_4 xdma_v4_1_8 xlconstant_v1_1_7 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_22 axi_vip_v1_1_8 gigantic_mux xlconcat_v2_1_4)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "SoC.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/opt/xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/opt/xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work gtwizard_ultrascale_v1_7_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/ip_0/sim/gtwizard_ultrascale_v1_7_gtye4_channel.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/ip_0/sim/SoC_xdma_0_0_pcie4c_ip_gt_gtye4_channel_wrapper.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/ip_0/sim/gtwizard_ultrascale_v1_7_gtye4_common.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/ip_0/sim/SoC_xdma_0_0_pcie4c_ip_gt_gtye4_common_wrapper.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/ip_0/sim/SoC_xdma_0_0_pcie4c_ip_gt_gtwizard_gtye4.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/ip_0/sim/SoC_xdma_0_0_pcie4c_ip_gt_gtwizard_top.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/ip_0/sim/SoC_xdma_0_0_pcie4c_ip_gt.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_cxs_remap.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_512b_async_fifo.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_512b_cc_intfc.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_512b_cc_output_mux.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_512b_cq_intfc.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_512b_cq_output_mux.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_512b_intfc_int.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_512b_intfc.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_512b_rc_intfc.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_512b_rc_output_mux.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_512b_rq_intfc.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_512b_rq_output_mux.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_512b_sync_fifo.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_bram_16k_int.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_bram_16k.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_bram_32k.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_bram_4k_int.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_bram_msix.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_bram_rep_int.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_bram_rep.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_bram_tph.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_bram.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_gtwizard_top.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_phy_ff_chain.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_phy_pipeline.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_gt_gt_channel.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_gt_gt_common.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_gt_phy_clk.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_gt_phy_rst.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_gt_phy_rxeq.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_gt_phy_txeq.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_sync_cell.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_sync.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_gt_cdr_ctrl_on_eidle.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_gt_receiver_detect_rxterm.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_gt_phy_wrapper.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_phy_top.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_init_ctrl.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_pl_eq.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_vf_decode.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_vf_decode_attr.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_pipe.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_seqnum_fifo.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_sys_clk_gen_ps.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source/SoC_xdma_0_0_pcie4c_ip_pcie4c_uscale_core_top.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/sim/SoC_xdma_0_0_pcie4c_ip.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_1/sim/xdma_v4_1_8_blk_mem_64_reg_be.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_2/sim/xdma_v4_1_8_blk_mem_64_noreg_be.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xdma_v4_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/xdma_v4_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/xdma_v4_1/hdl/verilog/SoC_xdma_0_0_dma_bram_wrap.sv" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/xdma_v4_1/hdl/verilog/SoC_xdma_0_0_dma_bram_wrap_1024.sv" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/xdma_v4_1/hdl/verilog/SoC_xdma_0_0_dma_bram_wrap_2048.sv" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/xdma_v4_1/hdl/verilog/SoC_xdma_0_0_core_top.sv" \
    "$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/sim/SoC_xdma_0_0.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/SoC/ip/SoC_util_ds_buf_0/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/SoC/ip/SoC_util_ds_buf_0/sim/SoC_util_ds_buf_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/sim/bd_d7be.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_0/sim/bd_d7be_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_1/sim/bd_d7be_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_2/sim/bd_d7be_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_3/sim/bd_d7be_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_4/sim/bd_d7be_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_5/sim/bd_d7be_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_6/sim/bd_d7be_sarn_0.sv" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_7/sim/bd_d7be_srn_0.sv" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_8/sim/bd_d7be_sawn_0.sv" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_9/sim/bd_d7be_swn_0.sv" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_10/sim/bd_d7be_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_11/sim/bd_d7be_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/7bd7/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_12/sim/bd_d7be_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_axi_smc_0/sim/SoC_axi_smc_0.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/hdl/QuantLaneNet_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/adder_tree.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/block_ram_dual_port.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/block_ram_multi_word.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/block_ram_multi_word_dual_port.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/block_ram_single_port.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/conv.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/fifo_64bits_to_fifo_24bits_input.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/fifo_64bits_to_mem_16bits_weight.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/fifo_counter.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/fifo_dual_read.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/fifo_single_read.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/kernel_write_assist.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/line_buffer.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/line_buffer_controller.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/line_buffer_datapath.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/macc_8bit_dual.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/macc_8bit_single.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/macc_8bit_single_1_to_n.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/model.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/mult_8bit_dual.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/pe_controller.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/pe_incha_double.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/pe_incha_obuffer.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/pe_incha_quadruple.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/pe_incha_single.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/pe_outcha_double.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/pe_outcha_double_controller.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/pe_outcha_double_obuffer.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/pe_outcha_single.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/post_process.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/sigmoid.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/src/top.v" \
    "$ref_dir/../../../bd/SoC/ipshared/802b/hdl/QuantLaneNet_v1_0.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_QuantLaneNet_0_0/sim/SoC_QuantLaneNet_0_0.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/sim/bd_5c78.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_0/sim/bd_5c78_ila_lib_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gigantic_mux $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/d322/hdl/gigantic_mux_v1_0_cntr.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_1/bd_5c78_g_inst_0_gigantic_mux.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_1/sim/bd_5c78_g_inst_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ip/SoC_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../QuanNet_Alveo.gen/sources_1/bd/SoC/ipshared/c968/hdl/verilog" +incdir+"/opt/xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_2/sim/bd_5c78_slot_0_aw_0.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_3/sim/bd_5c78_slot_0_w_0.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_4/sim/bd_5c78_slot_0_b_0.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_5/sim/bd_5c78_slot_0_ar_0.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_6/sim/bd_5c78_slot_0_r_0.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_7/sim/bd_5c78_slot_1_aw_0.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_8/sim/bd_5c78_slot_1_w_0.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_9/sim/bd_5c78_slot_1_b_0.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_10/sim/bd_5c78_slot_1_ar_0.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_11/sim/bd_5c78_slot_1_r_0.v" \
    "$ref_dir/../../../bd/SoC/ip/SoC_system_ila_0_0/sim/SoC_system_ila_0_0.v" \
    "$ref_dir/../../../bd/SoC/sim/SoC.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.SoC xil_defaultlib.glbl -o SoC_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./SoC_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./SoC.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/hoailuan/Research/2023/proj-lane_detection_alveo/QuanNet_Alveo/QuanNet_Alveo.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key SoC_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc SoC_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./SoC.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: SoC.sh [-help]\n\
Usage: SoC.sh [-lib_map_path]\n\
Usage: SoC.sh [-reset_run]\n\
Usage: SoC.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
